version: "3.9"

services:
    app:
        build: .
        volumes:
            - .:/usr/src/app
        container_name: nestjs_backend
        restart: always
        ports:
            - 3000:3000
        env_file: .env
        command: "yarn start"
